import {useState} from "react"
import {useRoutes} from "react-router-dom"
import routes from "~react-pages" // auto-generated by vite-plugin-pages

function App() {
	const element = useRoutes(routes)
	return element
}

export default App
